Dropped the support for python 3.5
edx/edx-django-utils pull request #85
Opened 2020-12-11 13:46 UTC by Jawayria

Dropped the support for python 3.5

**JIRA:**
https://openedx.atlassian.net/browse/BOM-2162

2020-12-16 11:17 UTC, mraarif commented
@Jawayria please open a ticket for SRE to remove this pending/required (now obsolete) check so we can merge this PR

2020-12-23 15:32 UTC, UsamaSadiq requested changes

2020-12-23 15:32 UTC, UsamaSadiq commented on edx_django_utils/__init__.py
> +__version__ = "3.13.1"
It should be `3.14.0` to match the CHANGELOG entry.

2020-12-23 15:32 UTC, UsamaSadiq commented on requirements/constraints.txt
>  # stevedore 2.0.0 requires python >= 3.6
You should remove this constraint as well since we have moved to python38.

2020-12-24 05:20 UTC, UsamaSadiq approved these changes

2020-12-24 05:43 UTC, mraarif approved these changes

2020-12-24 06:37 UTC, merged